apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: pod2
      image: poddos-image:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 5000
      command: ["node"]
      args: ["index.js"]
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
        requests:
          cpu: "0.5"
          memory: "256Mi"

